# Generated by Django 6.1.1 on 2026-09-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('roll_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('date_of_admission', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
