# Generated by Django 6.1.1 on 2026-09-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=200)),
                ('s_phone', models.CharField(max_length=200)),
                ('s_email', models.EmailField(max_length=254)),
                ('s_marks', models.IntegerField()),
            ],
        ),
    ]
